site_name: FSO - notes
copyright: 2022 Nicolas Souza
repo_name: FSO-notes
repo_url: https://github.com/nszchagas/FSO-notes

theme:
  name: material
  logo: _static/dino.png
  favicon: _static/dino.png
  features:
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - About: index.md
  - Overview: summaries/ch1.md
  - Operational Systems: summaries/ch2.md
  - Processes: summaries/ch3.md
  - Threads: summaries/ch4.md
  - Process Synchronization: summaries/ch5.md
  - CPU Scheduling: summaries/ch6.md
  - Main Memory: summaries/ch7.md
  - Virtual Memory: summaries/ch8.md
  - Mass-Storage Structure: summaries/ch9.md
