site_name: Fundamentos de Sistemas Operacionais
copyright: 2022 Nicolas Souza
repo_name: FSO-notes
repo_url: https://github.com/nszchagas/FSO-notes

theme:
  name: material
  logo: _static/icon.png
  features:
    - content.code.annotate
    - content.code.copy
  favicon: _static/icon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["codes"]
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - About: index.md
  - SILBERSCHATZ:
      - Chapter 1: summaries/ch1.md
      - Chapter 2: summaries/ch2.md
      - Chapter 3: summaries/ch3.md
      - Chapter 4: summaries/ch4.md
      - Chapter 5: summaries/ch5.md
      - Chapter 9: summaries/ch9.md
  - TANENBAUM:
      - M贸dulo 1: resumos/mod1.md
      - Processos: resumos/mod2.md
      - M贸dulo 3: resumos/mod3.md
      - M贸dulo 4: resumos/mod4.md
      - M贸dulo 5: resumos/mod5.md
