site_name: FSO - notes
copyright: 2022 Nicolas Souza

theme:
  name: material
  logo: _static/dino.png
  favicon: _static/dino.png
  features:
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - About: index.md
  - Overview: summaries/ch1.md
  - Operational Systems: summaries/ch2.md
  - Processes: summaries/ch3.md
  - Threads: summaries/ch4.md

  - Exercises: misc/exercises.md
