#!/bin/bash

if [[ $# -lt 1 ]]; then
	echo "Provide file to compile and input"
	exit 1
elif [[ $# -eq 2  ]]; then 
	file=$1
	input=$2
else 
	file=$1
	input=input
fi

echo "Running $file with input $input"
gcc $file

./a.out <$input

rm a.out
