name: lint
on:
  commit:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  lint:
  stage: linting
  image: registry.gitlab.com/pipeline-components/markdownlint:latest
  script:
    - mdl --style all --warnings .
